language: node_js
sudo: required # We must use sudo here to have rabbitmq running :(
dist: trusty # for a newer rabbtimq
env:
  global:
  - DEBUG='*,-babel*,-mocha*,-eslint*'
  - CXX=g++-4.8
  - RABBIT_USERNAME=guest
  - RABBIT_PASSWORD=guest
  - RABBIT_BASE_URL=http://localhost:15672/api 
node_js:
- '7'
cache:
  yarn: true
  directories:
    - node_modules
services:
  - rabbitmq
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
script: yarn test
